version: 2
updates:
  - package-ecosystem: pip
    directory: /requirements
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /webui
    schedule:
      interval: weekly
    labels:
      - dependencies
